### ISSUE TITLE
Not deleting upgrade directory

### ISSUE THREAD

**Issue by blackdynamite595** [chef-cookbooks/omnibus_updater#143]
```
#<Errno::ENOTEMPTY: directory[c:/opscode/chef.upgrade] (omnibus_updater::installer line 36) had an error: Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - c:/opscode/chef.upgrade> had an error:
directory[c:/opscode/chef.upgrade] (omnibus_updater::installer line 36) had an error: Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - c:/opscode/chef.upgrade
```

Seeing this error for every omnibus run.

**Comment by rbobrowicz** [comment]
I just started running into this issue as well. In our case the directory cleanup fails because of a locked file that is preventing the directory from being deleted. Which gives the above error on the next chef run. The file in question is: `C:\opscode\chef.upgrade\embedded\lib\ruby\gems\2.1.0\gems\chef-12.10.24-universal-mingw32\ext\win32-eventlog\chef-log.dll`

**Comment by OxHobbs** [comment]
I have the same issue running on Windows Server 2012 R2.  I seem to be getting successful client runs after a reboot.

**Comment by tas50** [comment]
At this time we've chosen to deprecate the omnibus_updater cookbook in favor of our new chef_client_updater cookbook. I'm going to close this issue out as we will not be updating or releasing new versions of this codebase. Check out the new code at https://github.com/chef-cookbooks/chef_client_updater
